# Generated by Django 5.2.16 on 2026-07-29 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='시험기간명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('status', models.CharField(choices=[('draft', '작성 중'), ('active', '진행 중'), ('completed', '완료'), ('archived', '보관')], default='draft', max_length=20, verbose_name='시험기간 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_periods', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '시험기간',
                'verbose_name_plural': '시험기간 목록',
                'db_table': 'exam_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='과목명')),
                ('exam_date', models.DateField(verbose_name='시험일')),
                ('priority', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='과목 우선순위')),
                ('speed_factor', models.FloatField(default=1.0, verbose_name='공부 속도 보정계수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('exam_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examperiod', verbose_name='시험기간')),
            ],
            options={
                'verbose_name': '시험 과목',
                'verbose_name_plural': '시험 과목 목록',
                'db_table': 'exams',
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='자료/범위명')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF 파일'), ('text', '텍스트 직접 입력')], default='text', max_length=10, verbose_name='자료 입력 유형')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/', verbose_name='첨부 파일(PDF)')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='추출된 텍스트 내용')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='텍스트 추출 상태')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='추출/파싱 실패 원인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='exams.exam', verbose_name='시험 과목')),
            ],
            options={
                'verbose_name': '학습 자료',
                'verbose_name_plural': '학습 자료 목록',
                'db_table': 'study_materials',
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='단원명')),
                ('title', models.CharField(max_length=200, verbose_name='학습 작업명')),
                ('task_type', models.CharField(choices=[('concept', '개념 학습'), ('practice', '문제 풀이'), ('review', '복습'), ('summary', '요약 정리'), ('custom', '기타/직접 입력')], default='concept', max_length=20, verbose_name='작업 유형')),
                ('importance', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='중요도')),
                ('depth', models.CharField(choices=[('core', '핵심'), ('basic', '기본'), ('optional', '선택')], default='basic', max_length=10, verbose_name='학습 깊이')),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움')], default='normal', max_length=10, verbose_name='난이도')),
                ('estimated_min_minutes', models.PositiveIntegerField(default=0, verbose_name='최소 예상시간(분)')),
                ('estimated_max_minutes', models.PositiveIntegerField(default=0, verbose_name='최대 예상시간(분)')),
                ('ai_reason', models.TextField(blank=True, null=True, verbose_name='AI 추천 이유')),
                ('is_user_modified', models.BooleanField(default=False, verbose_name='사용자 직접 수정 여부')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='작업 확정 여부')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='작업 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to='exams.exam', verbose_name='시험 과목')),
                ('study_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_tasks', to='exams.studymaterial', verbose_name='관련 학습 자료')),
            ],
            options={
                'verbose_name': '학습 작업',
                'verbose_name_plural': '학습 작업 목록',
                'db_table': 'study_tasks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('available_minutes', models.PositiveIntegerField(default=0, verbose_name='공부 가능시간(분)')),
                ('exam_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='exams.examperiod', verbose_name='시험기간')),
            ],
            options={
                'verbose_name': '날짜별 가용시간',
                'verbose_name_plural': '날짜별 가용시간 목록',
                'db_table': 'available_times',
                'ordering': ['date'],
                'unique_together': {('exam_period', 'date')},
            },
        ),
    ]
