# Generated by Django 5.2.16 on 2026-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='analysis_error_message',
            field=models.TextField(blank=True, null=True, verbose_name='AI 분석 실패 사유'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='analysis_retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='AI 분석 사용자 재시도 횟수'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='analysis_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='AI 분석 상태'),
        ),
    ]
