# Generated by Django 5.2.16 on 2026-07-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='importance',
        ),
        migrations.AddField(
            model_name='exam',
            name='priority',
            field=models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='과목 우선순위'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='추출/파싱 실패 원인'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF 파일'), ('text', '텍스트 직접 입력')], default='text', max_length=10, verbose_name='자료 입력 유형'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='status',
            field=models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='텍스트 추출 상태'),
        ),
        migrations.AddField(
            model_name='studytask',
            name='is_user_modified',
            field=models.BooleanField(default=False, verbose_name='사용자 직접 수정 여부'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examperiod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='task_type',
            field=models.CharField(choices=[('concept', '개념 학습'), ('practice', '문제 풀이'), ('review', '복습'), ('summary', '요약 정리'), ('custom', '기타/직접 입력')], default='concept', max_length=20, verbose_name='작업 유형'),
        ),
    ]
