# Generated by Django 5.2.16 on 2026-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studymaterial_analysis_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='analysis_run_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='AI 분석 실행 식별자'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI 분석 시작 시각'),
        ),
    ]
