# Generated by Django 5.2.16 on 2026-08-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_studymaterial_analysis_run_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='source_pages',
            field=models.JSONField(blank=True, default=list, verbose_name='근거 PDF 페이지 목록'),
        ),
    ]
