# Generated by Django 5.2.16 on 2026-08-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_studytask_source_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='extraction_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF 추출 시작 시각'),
        ),
    ]
