# Generated by Django 5.2.16 on 2026-08-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studymaterial_extraction_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='extraction_run_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='PDF 추출 실행 식별자'),
        ),
    ]
