# Generated by Django 5.2.17 on 2026-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_studymaterial_extraction_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='user_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
