# Generated by Django 5.2.17 on 2026-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_studymaterial_user_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='user_error_message',
            field=models.TextField(blank=True, null=True, verbose_name='추출 실패 시 사용자 노출용 메시지'),
        ),
    ]
