# Generated by Django 6.0.7 on 2026-07-27 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_minutes', models.PositiveIntegerField()),
                ('planned_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', '계획됨'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('AT_RISK', '위험')], default='PLANNED', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='exams.exam')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_minutes', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', '계획됨'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('AT_RISK', '위험')], default='PLANNED', max_length=20)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.dailyplan')),
                ('study_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='exams.studytask')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.CharField(choices=[('DONE', '완료'), ('PARTIAL', '일부완료'), ('NOT_DONE', '못함')], max_length=20)),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('daily_plan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_log', to='planner.dailyplanitem')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('recovery_type', models.CharField(choices=[('MAINTAIN_VOLUME', '분량 유지형'), ('CORE_FOCUS', '핵심 집중형')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '선택 대기'), ('APPLIED', '적용됨'), ('DISCARDED', '미채택')], default='PENDING', max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plans', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(blank=True, null=True)),
                ('changed_date', models.DateField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('RESCHEDULE', '재배치'), ('EXCLUDE', '제외')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('recovery_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.recoveryplan')),
                ('study_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_items', to='exams.studytask')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyplan',
            constraint=models.UniqueConstraint(fields=('exam', 'date'), name='unique_exam_daily_plan_date'),
        ),
    ]
