# Generated by Django 5.2.16 on 2026-07-29 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_minutes', models.PositiveIntegerField()),
                ('planned_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('planned', '계획됨'), ('in_progress', '진행중'), ('completed', '완료'), ('at_risk', '위험')], default='planned', max_length=20)),
                ('exam_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='exams.examperiod')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_minutes', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('planned', '계획됨'), ('in_progress', '진행중'), ('completed', '완료'), ('at_risk', '위험')], default='planned', max_length=20)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.dailyplan')),
                ('study_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='exams.studytask')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.CharField(choices=[('done', '완료'), ('partial', '일부완료'), ('not_done', '못함')], max_length=20)),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('daily_plan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_log', to='planner.dailyplanitem')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('recovery_type', models.CharField(choices=[('maintain_volume', '분량 유지형'), ('core_focus', '핵심 집중형')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '선택 대기'), ('applied', '적용됨'), ('discarded', '미채택')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('exam_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plans', to='exams.examperiod')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(blank=True, null=True)),
                ('changed_date', models.DateField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('reschedule', '재배치'), ('exclude', '제외')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('recovery_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.recoveryplan')),
                ('study_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_items', to='exams.studytask')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyplan',
            constraint=models.UniqueConstraint(fields=('exam_period', 'date'), name='unique_daily_plan_per_exam_period_date'),
        ),
    ]
