# Generated by Django 5.2.16 on 2026-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoveryplanitem',
            name='remaining_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
