# Generated by Django 5.2.16 on 2026-08-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('planner', '0002_dailyplan_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryplan',
            name='source_daily_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plans', to='planner.dailyplan'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='recoveryplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'applied')), fields=('recovery_group_id',), name='unique_applied_recovery_plan_per_group'),
        ),
    ]
