# Generated by Django 5.2.16 on 2026-08-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('planner', '0002_dailyplan_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recoveryplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'applied')), fields=('recovery_group_id',), name='unique_applied_recovery_plan_per_group'),
        ),
    ]
