# Generated by Django 5.2.16 on 2026-08-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_recoveryplan_source_daily_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryplanitem',
            name='source_daily_plan_item',
            field=models.ForeignKey(blank=True, help_text='이 복구 항목이 원래 있던 DailyPlanItem. None이면 실패한 작업을 새로 배치하는 것이고, 값이 있으면 학습 순서 보존을 위해 기존에 배치돼 있던 미래 작업을 이동시키는 것이다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_source_items', to='planner.dailyplanitem'),
        ),
    ]
