# Generated by Django 5.2.16 on 2026-08-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_recoveryplanitem_source_daily_plan_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryplanitem',
            name='is_carry_along',
            field=models.BooleanField(default=False, help_text="학습 순서 보존을 위해 함께 재배치/제외되는 후속 작업이면 True. source_daily_plan_item은 원본이 삭제되면 SET_NULL로 None이 되므로, carry-along 여부 자체는 이 필드로 별도 보존한다 (FK 값만으로는 '원래 실패 작업'과 '원본이 사라진 carry-along'을 구분할 수 없다)."),
        ),
    ]
